action_id: trunk-share-with-everyone
date: 2024-09-28 06:19:39
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: "\x1b[1m\x1b[31m✖ Please run 'trunk init' to setup trunk in this repository.\x1b[0m\n"
  err: ""
timestamp: 1727504379
full_timestamp:
  nanos: 716515000
  seconds: 1727504379
trunk_version: 1.22.5
